# Generated by Django 4.1.5 on 2023-02-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.CharField(max_length=5000, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('impact', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.application')),
                ('parent_feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FeedbackIngestion.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='IntercomFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('playstore', 'PlayStore'), ('twitter', 'Twitter'), ('intercom', 'Intercom'), ('S04', 'Discourse')], max_length=100)),
                ('language', models.CharField(blank=True, max_length=5000, null=True)),
                ('feedback_created_timestamp', models.DateTimeField()),
                ('feedback_updated_timestamp', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.application')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeedbackIngestion.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='DiscourseFeedbackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_post_timestamp', models.DateField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.application')),
            ],
        ),
    ]
