# Generated by Django 4.1.5 on 2023-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedbackIngestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaystoreFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.BigIntegerField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('review_title', models.TextField(blank=True, null=True)),
                ('review_description', models.TextField(blank=True, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-feedback_id',)},
        ),
        migrations.DeleteModel(
            name='DiscourseFeedbackInfo',
        ),
    ]
