# Generated by Django 4.1.5 on 2023-02-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FeedbackIngestion', '0002_playstorefeedback_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaystoreFeedback',
        ),
        migrations.RemoveField(
            model_name='feedbackmetadata',
            name='application',
        ),
        migrations.AlterField(
            model_name='feedbackmetadata',
            name='feedback',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FeedbackIngestion.feedback'),
        ),
        migrations.AlterField(
            model_name='feedbackmetadata',
            name='source',
            field=models.CharField(choices=[('S03', 'PlayStore'), ('S01', 'Twitter'), ('S02', 'Intercom'), ('S04', 'Discourse')], max_length=100),
        ),
    ]
