# Generated by Django 4.1.5 on 2023-02-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiscourseIngestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoursefeedbackinfo',
            name='last_post_timestamp',
            field=models.DateTimeField(),
        ),
    ]
