# Generated by Django 4.1.5 on 2023-02-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaystoreFeedbackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_post_timestamp', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.application')),
            ],
        ),
        migrations.CreateModel(
            name='PlaystoreFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.CharField(blank=True, max_length=100, null=True)),
                ('review_id', models.CharField(max_length=100)),
                ('parent_review_id', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ratings', models.IntegerField(blank=True, null=True)),
                ('created_at_playstore', models.DateTimeField(blank=True, null=True)),
                ('updated_at_playstore', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
