# Generated by Django 4.1.5 on 2023-02-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discourseregistration',
            name='app',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.application'),
        ),
        migrations.AlterField(
            model_name='playstoreregistration',
            name='app',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.application'),
        ),
        migrations.AlterField(
            model_name='twitterregistration',
            name='app',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.application'),
        ),
        migrations.CreateModel(
            name='IntercomRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(max_length=5000, null=True)),
                ('secret_key', models.CharField(max_length=5000, null=True)),
                ('integration_type', models.CharField(choices=[('P01', 'PULL MODEL'), ('P02', 'PUSH MODEL')], max_length=3)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Client.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
