# Generated by Django 4.1.5 on 2023-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_discourseregistration_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discourseregistration',
            name='access_id',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='discourseregistration',
            name='secret_key',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='intercomregistration',
            name='access_id',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='intercomregistration',
            name='secret_key',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='playstoreregistration',
            name='access_id',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='playstoreregistration',
            name='secret_key',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='twitterregistration',
            name='access_id',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='twitterregistration',
            name='secret_key',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
